#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="LotusDB")]
	public partial class LotusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertform_data(form_data instance);
    partial void Updateform_data(form_data instance);
    partial void Deleteform_data(form_data instance);
    partial void Insertform_data_impression(form_data_impression instance);
    partial void Updateform_data_impression(form_data_impression instance);
    partial void Deleteform_data_impression(form_data_impression instance);
    partial void Insertform_field_value(form_field_value instance);
    partial void Updateform_field_value(form_field_value instance);
    partial void Deleteform_field_value(form_field_value instance);
    partial void Insertform_setting(form_setting instance);
    partial void Updateform_setting(form_setting instance);
    partial void Deleteform_setting(form_setting instance);
    partial void Insertform_field_definition(form_field_definition instance);
    partial void Updateform_field_definition(form_field_definition instance);
    partial void Deleteform_field_definition(form_field_definition instance);
    #endregion
		
		public LotusDataContext() : 
				base(global::Services.Properties.Settings.Default.LotusDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LotusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LotusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LotusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LotusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<form_data> form_datas
		{
			get
			{
				return this.GetTable<form_data>();
			}
		}
		
		public System.Data.Linq.Table<form_data_impression> form_data_impressions
		{
			get
			{
				return this.GetTable<form_data_impression>();
			}
		}
		
		public System.Data.Linq.Table<form_field_value> form_field_values
		{
			get
			{
				return this.GetTable<form_field_value>();
			}
		}
		
		public System.Data.Linq.Table<form_setting> form_settings
		{
			get
			{
				return this.GetTable<form_setting>();
			}
		}
		
		public System.Data.Linq.Table<form_field_definition> form_field_definitions
		{
			get
			{
				return this.GetTable<form_field_definition>();
			}
		}
		
		public System.Data.Linq.Table<container> containers
		{
			get
			{
				return this.GetTable<container>();
			}
		}
	}
	
	[Table(Name="dbo.form_data")]
	public partial class form_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _form_data_id;
		
		private int _page_id;
		
		private int _form_field_definition_id;
		
		private string _value1;
		
		private string _value2;
		
		private System.Nullable<bool> _value3;
		
		private System.Nullable<decimal> _value4;
		
		private System.Nullable<decimal> _value5;
		
		private System.Nullable<System.DateTime> _value6;
		
		private System.Nullable<System.DateTime> _submitted_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_data_idChanging(int value);
    partial void Onform_data_idChanged();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void Onform_field_definition_idChanging(int value);
    partial void Onform_field_definition_idChanged();
    partial void Onvalue1Changing(string value);
    partial void Onvalue1Changed();
    partial void Onvalue2Changing(string value);
    partial void Onvalue2Changed();
    partial void Onvalue3Changing(System.Nullable<bool> value);
    partial void Onvalue3Changed();
    partial void Onvalue4Changing(System.Nullable<decimal> value);
    partial void Onvalue4Changed();
    partial void Onvalue5Changing(System.Nullable<decimal> value);
    partial void Onvalue5Changed();
    partial void Onvalue6Changing(System.Nullable<System.DateTime> value);
    partial void Onvalue6Changed();
    partial void Onsubmitted_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onsubmitted_dateChanged();
    #endregion
		
		public form_data()
		{
			OnCreated();
		}
		
		[Column(Storage="_form_data_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int form_data_id
		{
			get
			{
				return this._form_data_id;
			}
			set
			{
				if ((this._form_data_id != value))
				{
					this.Onform_data_idChanging(value);
					this.SendPropertyChanging();
					this._form_data_id = value;
					this.SendPropertyChanged("form_data_id");
					this.Onform_data_idChanged();
				}
			}
		}
		
		[Column(Storage="_page_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[Column(Storage="_form_field_definition_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int form_field_definition_id
		{
			get
			{
				return this._form_field_definition_id;
			}
			set
			{
				if ((this._form_field_definition_id != value))
				{
					this.Onform_field_definition_idChanging(value);
					this.SendPropertyChanging();
					this._form_field_definition_id = value;
					this.SendPropertyChanged("form_field_definition_id");
					this.Onform_field_definition_idChanged();
				}
			}
		}
		
		[Column(Storage="_value1", DbType="NVarChar(255)")]
		public string value1
		{
			get
			{
				return this._value1;
			}
			set
			{
				if ((this._value1 != value))
				{
					this.Onvalue1Changing(value);
					this.SendPropertyChanging();
					this._value1 = value;
					this.SendPropertyChanged("value1");
					this.Onvalue1Changed();
				}
			}
		}
		
		[Column(Storage="_value2", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string value2
		{
			get
			{
				return this._value2;
			}
			set
			{
				if ((this._value2 != value))
				{
					this.Onvalue2Changing(value);
					this.SendPropertyChanging();
					this._value2 = value;
					this.SendPropertyChanged("value2");
					this.Onvalue2Changed();
				}
			}
		}
		
		[Column(Storage="_value3", DbType="Bit")]
		public System.Nullable<bool> value3
		{
			get
			{
				return this._value3;
			}
			set
			{
				if ((this._value3 != value))
				{
					this.Onvalue3Changing(value);
					this.SendPropertyChanging();
					this._value3 = value;
					this.SendPropertyChanged("value3");
					this.Onvalue3Changed();
				}
			}
		}
		
		[Column(Storage="_value4", DbType="Money")]
		public System.Nullable<decimal> value4
		{
			get
			{
				return this._value4;
			}
			set
			{
				if ((this._value4 != value))
				{
					this.Onvalue4Changing(value);
					this.SendPropertyChanging();
					this._value4 = value;
					this.SendPropertyChanged("value4");
					this.Onvalue4Changed();
				}
			}
		}
		
		[Column(Storage="_value5", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> value5
		{
			get
			{
				return this._value5;
			}
			set
			{
				if ((this._value5 != value))
				{
					this.Onvalue5Changing(value);
					this.SendPropertyChanging();
					this._value5 = value;
					this.SendPropertyChanged("value5");
					this.Onvalue5Changed();
				}
			}
		}
		
		[Column(Storage="_value6", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> value6
		{
			get
			{
				return this._value6;
			}
			set
			{
				if ((this._value6 != value))
				{
					this.Onvalue6Changing(value);
					this.SendPropertyChanging();
					this._value6 = value;
					this.SendPropertyChanged("value6");
					this.Onvalue6Changed();
				}
			}
		}
		
		[Column(Storage="_submitted_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> submitted_date
		{
			get
			{
				return this._submitted_date;
			}
			set
			{
				if ((this._submitted_date != value))
				{
					this.Onsubmitted_dateChanging(value);
					this.SendPropertyChanging();
					this._submitted_date = value;
					this.SendPropertyChanged("submitted_date");
					this.Onsubmitted_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.form_data_impressions")]
	public partial class form_data_impression : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _form_data_id;
		
		private int _page_id;
		
		private System.Nullable<int> _impressions;
		
		private System.Nullable<System.DateTime> _impression_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_data_idChanging(int value);
    partial void Onform_data_idChanged();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void OnimpressionsChanging(System.Nullable<int> value);
    partial void OnimpressionsChanged();
    partial void Onimpression_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onimpression_dateChanged();
    #endregion
		
		public form_data_impression()
		{
			OnCreated();
		}
		
		[Column(Storage="_form_data_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int form_data_id
		{
			get
			{
				return this._form_data_id;
			}
			set
			{
				if ((this._form_data_id != value))
				{
					this.Onform_data_idChanging(value);
					this.SendPropertyChanging();
					this._form_data_id = value;
					this.SendPropertyChanged("form_data_id");
					this.Onform_data_idChanged();
				}
			}
		}
		
		[Column(Storage="_page_id", DbType="Int NOT NULL")]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[Column(Storage="_impressions", DbType="Int")]
		public System.Nullable<int> impressions
		{
			get
			{
				return this._impressions;
			}
			set
			{
				if ((this._impressions != value))
				{
					this.OnimpressionsChanging(value);
					this.SendPropertyChanging();
					this._impressions = value;
					this.SendPropertyChanged("impressions");
					this.OnimpressionsChanged();
				}
			}
		}
		
		[Column(Storage="_impression_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> impression_date
		{
			get
			{
				return this._impression_date;
			}
			set
			{
				if ((this._impression_date != value))
				{
					this.Onimpression_dateChanging(value);
					this.SendPropertyChanging();
					this._impression_date = value;
					this.SendPropertyChanged("impression_date");
					this.Onimpression_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.form_field_values")]
	public partial class form_field_value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _form_field_value_id;
		
		private int _form_field_definition_id;
		
		private string _display_value;
		
		private System.Nullable<bool> _is_default;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_field_value_idChanging(int value);
    partial void Onform_field_value_idChanged();
    partial void Onform_field_definition_idChanging(int value);
    partial void Onform_field_definition_idChanged();
    partial void Ondisplay_valueChanging(string value);
    partial void Ondisplay_valueChanged();
    partial void Onis_defaultChanging(System.Nullable<bool> value);
    partial void Onis_defaultChanged();
    #endregion
		
		public form_field_value()
		{
			OnCreated();
		}
		
		[Column(Storage="_form_field_value_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int form_field_value_id
		{
			get
			{
				return this._form_field_value_id;
			}
			set
			{
				if ((this._form_field_value_id != value))
				{
					this.Onform_field_value_idChanging(value);
					this.SendPropertyChanging();
					this._form_field_value_id = value;
					this.SendPropertyChanged("form_field_value_id");
					this.Onform_field_value_idChanged();
				}
			}
		}
		
		[Column(Storage="_form_field_definition_id", DbType="Int NOT NULL")]
		public int form_field_definition_id
		{
			get
			{
				return this._form_field_definition_id;
			}
			set
			{
				if ((this._form_field_definition_id != value))
				{
					this.Onform_field_definition_idChanging(value);
					this.SendPropertyChanging();
					this._form_field_definition_id = value;
					this.SendPropertyChanged("form_field_definition_id");
					this.Onform_field_definition_idChanged();
				}
			}
		}
		
		[Column(Storage="_display_value", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string display_value
		{
			get
			{
				return this._display_value;
			}
			set
			{
				if ((this._display_value != value))
				{
					this.Ondisplay_valueChanging(value);
					this.SendPropertyChanging();
					this._display_value = value;
					this.SendPropertyChanged("display_value");
					this.Ondisplay_valueChanged();
				}
			}
		}
		
		[Column(Storage="_is_default", DbType="Bit")]
		public System.Nullable<bool> is_default
		{
			get
			{
				return this._is_default;
			}
			set
			{
				if ((this._is_default != value))
				{
					this.Onis_defaultChanging(value);
					this.SendPropertyChanging();
					this._is_default = value;
					this.SendPropertyChanged("is_default");
					this.Onis_defaultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.form_settings")]
	public partial class form_setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _page_id;
		
		private string _header;
		
		private string _footer;
		
		private string _thank_you_message;
		
		private System.Nullable<bool> _return_to_form;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void OnheaderChanging(string value);
    partial void OnheaderChanged();
    partial void OnfooterChanging(string value);
    partial void OnfooterChanged();
    partial void Onthank_you_messageChanging(string value);
    partial void Onthank_you_messageChanged();
    partial void Onreturn_to_formChanging(System.Nullable<bool> value);
    partial void Onreturn_to_formChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public form_setting()
		{
			OnCreated();
		}
		
		[Column(Storage="_page_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[Column(Storage="_header", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string header
		{
			get
			{
				return this._header;
			}
			set
			{
				if ((this._header != value))
				{
					this.OnheaderChanging(value);
					this.SendPropertyChanging();
					this._header = value;
					this.SendPropertyChanged("header");
					this.OnheaderChanged();
				}
			}
		}
		
		[Column(Storage="_footer", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string footer
		{
			get
			{
				return this._footer;
			}
			set
			{
				if ((this._footer != value))
				{
					this.OnfooterChanging(value);
					this.SendPropertyChanging();
					this._footer = value;
					this.SendPropertyChanged("footer");
					this.OnfooterChanged();
				}
			}
		}
		
		[Column(Storage="_thank_you_message", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string thank_you_message
		{
			get
			{
				return this._thank_you_message;
			}
			set
			{
				if ((this._thank_you_message != value))
				{
					this.Onthank_you_messageChanging(value);
					this.SendPropertyChanging();
					this._thank_you_message = value;
					this.SendPropertyChanged("thank_you_message");
					this.Onthank_you_messageChanged();
				}
			}
		}
		
		[Column(Storage="_return_to_form", DbType="Bit")]
		public System.Nullable<bool> return_to_form
		{
			get
			{
				return this._return_to_form;
			}
			set
			{
				if ((this._return_to_form != value))
				{
					this.Onreturn_to_formChanging(value);
					this.SendPropertyChanging();
					this._return_to_form = value;
					this.SendPropertyChanged("return_to_form");
					this.Onreturn_to_formChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.form_field_definitions")]
	public partial class form_field_definition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _form_field_definition_id;
		
		private string _form_field_name;
		
		private int _sorting;
		
		private string _input_type;
		
		private System.Nullable<int> _width;
		
		private System.Nullable<int> _height;
		
		private string _default_value;
		
		private int _page_id;
		
		private bool _is_required;
		
		private string _div_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_field_definition_idChanging(int value);
    partial void Onform_field_definition_idChanged();
    partial void Onform_field_nameChanging(string value);
    partial void Onform_field_nameChanged();
    partial void OnsortingChanging(int value);
    partial void OnsortingChanged();
    partial void Oninput_typeChanging(string value);
    partial void Oninput_typeChanged();
    partial void OnwidthChanging(System.Nullable<int> value);
    partial void OnwidthChanged();
    partial void OnheightChanging(System.Nullable<int> value);
    partial void OnheightChanged();
    partial void Ondefault_valueChanging(string value);
    partial void Ondefault_valueChanged();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void Onis_requiredChanging(bool value);
    partial void Onis_requiredChanged();
    partial void Ondiv_idChanging(string value);
    partial void Ondiv_idChanged();
    #endregion
		
		public form_field_definition()
		{
			OnCreated();
		}
		
		[Column(Storage="_form_field_definition_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int form_field_definition_id
		{
			get
			{
				return this._form_field_definition_id;
			}
			set
			{
				if ((this._form_field_definition_id != value))
				{
					this.Onform_field_definition_idChanging(value);
					this.SendPropertyChanging();
					this._form_field_definition_id = value;
					this.SendPropertyChanged("form_field_definition_id");
					this.Onform_field_definition_idChanged();
				}
			}
		}
		
		[Column(Storage="_form_field_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string form_field_name
		{
			get
			{
				return this._form_field_name;
			}
			set
			{
				if ((this._form_field_name != value))
				{
					this.Onform_field_nameChanging(value);
					this.SendPropertyChanging();
					this._form_field_name = value;
					this.SendPropertyChanged("form_field_name");
					this.Onform_field_nameChanged();
				}
			}
		}
		
		[Column(Storage="_sorting", DbType="Int NOT NULL")]
		public int sorting
		{
			get
			{
				return this._sorting;
			}
			set
			{
				if ((this._sorting != value))
				{
					this.OnsortingChanging(value);
					this.SendPropertyChanging();
					this._sorting = value;
					this.SendPropertyChanged("sorting");
					this.OnsortingChanged();
				}
			}
		}
		
		[Column(Storage="_input_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string input_type
		{
			get
			{
				return this._input_type;
			}
			set
			{
				if ((this._input_type != value))
				{
					this.Oninput_typeChanging(value);
					this.SendPropertyChanging();
					this._input_type = value;
					this.SendPropertyChanged("input_type");
					this.Oninput_typeChanged();
				}
			}
		}
		
		[Column(Storage="_width", DbType="Int")]
		public System.Nullable<int> width
		{
			get
			{
				return this._width;
			}
			set
			{
				if ((this._width != value))
				{
					this.OnwidthChanging(value);
					this.SendPropertyChanging();
					this._width = value;
					this.SendPropertyChanged("width");
					this.OnwidthChanged();
				}
			}
		}
		
		[Column(Storage="_height", DbType="Int")]
		public System.Nullable<int> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[Column(Storage="_default_value", DbType="NVarChar(255)")]
		public string default_value
		{
			get
			{
				return this._default_value;
			}
			set
			{
				if ((this._default_value != value))
				{
					this.Ondefault_valueChanging(value);
					this.SendPropertyChanging();
					this._default_value = value;
					this.SendPropertyChanged("default_value");
					this.Ondefault_valueChanged();
				}
			}
		}
		
		[Column(Storage="_page_id", DbType="Int NOT NULL")]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[Column(Storage="_is_required", DbType="Bit NOT NULL")]
		public bool is_required
		{
			get
			{
				return this._is_required;
			}
			set
			{
				if ((this._is_required != value))
				{
					this.Onis_requiredChanging(value);
					this.SendPropertyChanging();
					this._is_required = value;
					this.SendPropertyChanged("is_required");
					this.Onis_requiredChanged();
				}
			}
		}
		
		[Column(Storage="_div_id", DbType="NVarChar(50)")]
		public string div_id
		{
			get
			{
				return this._div_id;
			}
			set
			{
				if ((this._div_id != value))
				{
					this.Ondiv_idChanging(value);
					this.SendPropertyChanging();
					this._div_id = value;
					this.SendPropertyChanged("div_id");
					this.Ondiv_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.containers")]
	public partial class container
	{
		
		private int _id;
		
		private string _name;
		
		public container()
		{
		}
		
		[Column(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
