<?xml version="1.0" encoding="utf-8"?>
<Database Name="LotusDB" Class="LotusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=LotusDB;Integrated Security=True" SettingsObjectName="Services.Properties.Settings" SettingsPropertyName="LotusDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.form_data_impressions" Member="form_data_impressions">
    <Type Name="form_data_impression">
      <Column Name="form_data_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="impressions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="impression_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.form_field_values" Member="form_field_values">
    <Type Name="form_field_value">
      <Column Name="form_field_value_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="form_field_definition_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="display_value" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="is_default" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.form_settings" Member="form_settings">
    <Type Name="form_setting">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="header" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="footer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="thank_you_message" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="return_to_form" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.containers" Member="containers">
    <Type Name="container">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sorting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.form_field_definitions" Member="form_field_definitions">
    <Type Name="form_field_definition">
      <Column Name="form_field_definition_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="form_field_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="sorting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="input_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_value" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="div_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.pages" Member="pages">
    <Type Name="page">
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sorting" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="channel_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="use_default_template" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="page_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="file_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="summary" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="picture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="link_text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="link_placement" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="content_left" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="content_body" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="content_right" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="file_attachment" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="file_size" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="owner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_updated_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_updated_by" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="published_start_date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="published_end_date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="meta_description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="is_hidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_system" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="page_module" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="use_discussion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="use_rating" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allow_links_crawled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allow_page_indexed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_marked_for_archival" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="editor_review_by" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publisher_review_by" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="display_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="properties" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="properties2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="https" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="root_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="event_all_day" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="event_start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sale_price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="weight" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="sku" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="units_in_stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="discount_percentage" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="use_comments" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_listing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="listing_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="listing_property" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="listing_datetime_format" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="listing_columns" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="listing_page_size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="link_target" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="is_link" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="listing_template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="listing_use_categories" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="elements" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="listing_elements" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="first_published_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="listing_default_order" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="file_view" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="file_view_listing" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="tangible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.form_data" Member="form_datas">
    <Type Name="form_data">
      <Column Name="form_data_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="form_field_definition_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="value1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="value2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="value3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="value4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="value5" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="value6" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="submitted_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.booking" Member="bookings">
    <Type Name="booking">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="form_data_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="submited_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>